export {
    setContestBackgroundImage,
    setContestCategory,
    setContestDateEnd,
    setContestDateStart,
    setContestDescription,
    setContestExampleMedia,
    setContestMaxAllowedParticipantAmount,
    setContestName,
    setContestOwner,
    setContestParticipantAmount,
    setContestPrizeStructure,
    setContestStatus,
    setContestSubcategory,
} from './dataSetters'
